# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base-nodejs/aarch64:0.2.5"
  armv7: "ghcr.io/hassio-addons/base-nodejs/armv7:0.2.5"
  amd64: "ghcr.io/hassio-addons/base-nodejs/amd64:0.2.5"
labels:
  org.opencontainers.image.title: "MCZ Maestro Integration"
  org.opencontainers.image.description: "MCZ Stove Integration only for Maestro V1 (old version)"
  org.opencontainers.image.source: "https://github.com/bertrandgressier/mcz-stove-gateway"
  org.opencontainers.image.licenses: "MIT"

