---
name: MCZ Maestro Integration
description: MCZ Stove Integration only for Maestro V1 (old version)
version: 1.0.0
slug: mcz-maestro
init: false
url: https://github.com/bertrandgressier/mcz-stove-gateway/tree/main/hassio-mcz-maestro
map:
  - share:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: "ghcr.io/bertrandgressier/{arch}-addon-hassio-mcz-maestro"
