---
name: MCZ Maestro Integration
description: MCZ Stove Integration only for Maestro V1 (old version)
version: 1.0.1
slug: mcz-maestro
init: false
url: https://github.com/bertrandgressier/mcz-stove-gateway/tree/main/hassio-mcz-maestro
arch:
  - armv7
  - aarch64
  - amd64
image: "ghcr.io/bertrandgressier/{arch}-addon-hassio-mcz-maestro"
