name: MCZ Maestro Integration - DEV
description: MCZ Stove Integration only for Maestro V1 (old version) - Dev version
version: dev
slug: hassio-mcz-maestro-dev
init: false
url: https://github.com/bertrandgressier/mcz-stove-gateway/tree/main/hassio-mcz-maestro-dev
arch:
  - armv7
  - aarch64
  - amd64
options:
  setup:
    debug: false
  mqtt:
    url: "mqtt://core-mosquitto"
    username: ""
    password: ""
    mqttTopicPath: "MczStove"
  ws:
    url: "http://app.mcz.it:9000"
  stoves:
    - serialNumber: 12345678
      macAddress: "XXXXXXXXXXXX"
schema:
  setup:
    debug: bool
  mqtt:
    url: url
    username: str
    password: password
    mqttTopicPath: str
  ws:
    url: url
  stoves:
    - serialNumber: int
      macAddress: str
image: "ghcr.io/bertrandgressier/{arch}-addon-hassio-mcz-maestro-dev"
